dist: xenial
language: java

branches:
  only:
    - master

jdk:
  - openjdk8
  - openjdk11

matrix:
  allow_failures:
    - jdk: openjdk11

before_install:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"
 - "export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=warn"

script:
 - mvn install -B -V
 - mvn javadoc:jar

after_success:
  - bash <(curl -s https://codecov.io/bash)
